flights_analytics_dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: lunar-outlet-456701-t7
      dataset: airflow_stg_bq_dataset
      threads: 1
      keyfile: /opt/airflow/keys/gcp_credentials.json
      timeout_seconds: 400
      location: asia-southeast1
